### ISSUE TITLE
Function missing?

### ISSUE THREAD

**Issue by massih10** [Tung-I/Dual-awareness-Attention-for-Few-shot-Object-Detection#12]
In model.roi_layers the functions do an import `from model import _C`. This function is nowhere declared, hence inference-test fails. Can you help out?

**Comment by michaelku1** [comment]
__C is not a function, it is an object created by EasyDictionary. It is basically a dictionary object for easy referencing in order to define various hyperparameters in the config.py file. So you can imagine all parameters defined in the config.py file are stored in this __C variable. Therefore, importing __C simply means importing this variable, and obviously with the initialised parameters. Hope that helps!

**Comment by massih10** [comment]
thanks, after using `pip install easydict` the error is gone.
